### ISSUE TITLE
Release new version autonormalize for Featuretools 1.0.0

### ISSUE THREAD

**Issue by gsheni** [alteryx/autonormalize#34]
- Release new version (2.0.0?) that is compatible with Featuretools 1.0.0. 
- This (autonormalize) should be **released before Featuretools**, making sure to set the Featuretools version to >=1.0.0 in requirements.txt to prevent installation before featuretools is released.

**Comment by gsheni** [comment]
@rwedge going to assign you to this issue, as we need to document the release process for this library (we don't have a release.md in the repo).

**Comment by rwedge** [comment]
Version 2.0.0 has been released
